### ISSUE TITLE
502 Bad Gateway after upgrade

### ISSUE THREAD

**Issue by vcorreze** [YunoHost-Apps/shellinabox_ynh#9]
Bonjour,

Après mise à jour en *ynh 3.0.0.1/debian 9.4* shellinabox renvoie un `502 bad gateway`. (shellinabox était déjà installé). 

J'ai refait `yunohost app upgrade` qui n'a rien changé.

Mon manifest.json m'indique que j'ai bien la version 1.1.0 qui contient la PR #8 

Le problème se trouve ici : 
- dans **`/etc/yunohost/apps/shellinabox/conf/shellinabox`** la variable `SHELLINABOX_ARGS` contient bien l'option `--disable-ssl`
- dans **`/etc/default/shellinabox`** la variable **ne contient pas** cette option.

Il semble que la maj de yunohost ne modifie pas le fichier de conf dans defaut s'il existe. Quand je corrige manuellement, tout refonctionne.

Merci pour le boulot sur ynh, c'est génial.

**Comment by maniackcrudelis** [comment]
En effet, bien vu.
J'ai moi même ajouté `--disable-ssl` pour stretch, mais je n'ai pas vérifié le script d'upgrade qui oublie en effet de réappliquer la config.
Je vais corriger
